env:
  browser: true
  es2021: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  "@typescript-eslint/explicit-function-return-type": "warn",
  "@typescript-eslint/no-misused-promises": "off",
  "@typescript-eslint/strict-boolean-expressions" : "off",
  "@typescript-eslint/prefer-optional-chain": "warn",
  "no-throw-literal": "off",
  "@typescript-eslint/no-throw-literal": "off"
}
overrides:
  - files:
      - 'src/navigations/**/*tsx'
    rules:
      # https://reactnavigation.org/docs/typescript
      "@typescript-eslint/consistent-type-definitions": "off"
settings: {
  "react": {
    "version": "detect"
  }
}
extends:
  - standard-with-typescript
  - plugin:react/recommended
  - prettier
