env:
  browser: true
  es2021: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  "@typescript-eslint/explicit-function-return-type": "warn"
}
settings: {
  "react": {
    "version": "detect"
  }
}
extends:
  - standard-with-typescript
  - plugin:react/recommended
  - prettier
