# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: node:14

pipelines:
  default:
    - step:
        name: 'Install'
        script:
          - npm install
    - step:
        name: 'Lint'
        script:
          - npm run lint
